name: Release

on:
  push:
    tags: ["*"]

jobs:
  release:
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4.1.2
    - name: Create release
      uses: ncipollo/release-action@v1.14.0
